name: "Publisher"

on:
  push:
    tags: v**

jobs:
  build-and-upload:
    name: "Upload documentation, PyPI distribution"
    runs-on: ubuntu-latest
    env:
      OS: linux
      PYTHON: "3.8"
    steps:
      - name: "Prepare package metadata"
        run: |
          echo "VERSION=$(echo "${{ github.ref_name }}" | cut -dv -f2)" >> $GITHUB_ENV
          echo "PACKAGE=$(echo "${{ github.repository }}" | cut -d/ -f2 | tr '-' '_')" >> $GITHUB_ENV
      - name: "Checkout repository"
        uses: actions/checkout@v3
      - name: "Setup Python"
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON }}
      - name: "Build sdist"
        run: |
          python -m pip install --upgrade build
          python -m build
      - name: "Upload to PyPI"
        run: |
          python -m pip install --upgrade twine
          twine upload -u __token__ -p ${{ secrets.TESTPYPI_TOKEN }} --repository testpypi dist/${{ env.PACKAGE }}-${{ env.VERSION }}.tar.gz
