name: "Publisher"

on:
  schedule:
    - cron: "51 23 * * *"

jobs:
  check-updates:
    name: "Check recent updates"
    runs-on: ubuntu-latest
    outputs:
      recent: ${{ steps.get_recent.outputs.RECENT }}
    env:
      OS: linux
      PYTHON: "3.8"
    steps:
      - name: "Get pushes in the last 24 hours"
        id: get_recent
        run: |
          if ["$(git reflog --since='24 hours ago')" == '']; then 
            echo "RECENT=false" >> $GITHUB_OUTPUT; 
          else 
            echo "RECENT=true" >> $GITHUB_OUTPUT; 
          fi

  build-and-upload:
    name: "Upload documentation, PyPI distribution"
    needs: [check-updates]
    if: needs.check-updates.outputs.recent == 'true'
    runs-on: ubuntu-latest
    env:
      OS: linux
      PYTHON: "3.8"
    steps:
      - name: "Prepare package metadata"
        run: |
          echo "VERSION=$(echo "${{ github.ref_name }}" | cut -dv -f2)" >> $GITHUB_ENV
          echo "PACKAGE=$(echo "${{ github.repository }}" | cut -d/ -f2 | tr '-' '_')" >> $GITHUB_ENV
      - name: "Checkout repository"
        uses: actions/checkout@v3
      - name: "Setup Python"
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON }}
      - name: "Build sdist"
        run: |
          python -m pip install --upgrade build
          python -m build
      - name: "Upload to PyPI"
        run: |
          python -m pip install --upgrade twine
          twine upload -u __token__ -p ${{ secrets.TESTPYPI_TOKEN }} --repository testpypi dist/${{ env.PACKAGE }}-${{ env.VERSION }}.tar.gz
